version: '3.9'

services:
  backend:
    build: ./backend
    container_name: graphql-backend
    ports:
      - '4000:4000'
    environment:
      - MONGODB_URI=mongodb://mongo:27017/usersdb
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  frontend:
    build: ./frontend
    container_name: graphql-frontend
    ports:
      - '5173:5173'
    depends_on:
      - backend
    environment:
      - VITE_GRAPHQL_ENDPOINT=http://localhost:4000/graphql
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  mongo_data:
